version: 2
jobs:
  build:
    working_directory: /go/src/github.com/upamune/vault-initializer
    docker:
    - image: golang:1.11.0
    steps:
    - checkout
    - run:
        name: install dep
        command: go get -u github.com/golang/dep/cmd/dep
    - restore_cache:
        key: vault-initializer-{{ checksum "Gopkg.lock" }}
    - run:
        name: deps
        command: |
          if [ ! -d 'vendor' ]; then
            dep ensure -vendor-only
          fi
    - save_cache:
        key: vault-initializer-{{ checksum "Gopkg.lock" }}
        paths:
          - /go/src/github.com/upamune/vault-initializer/vendor
    - run:
        name: go build
        command: CGO_ENABLE=0 GOOS=linux go build -ldflags="-s -w" -o vault-initializer -v .
workflows:
  version: 2
  build:
    jobs:
    - build
